[package]
name = "wav1c-ffi"
version = "0.1.0"
edition = "2024"
authors.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "lib"]

[dependencies]
wav1c = { path = "../wav1c" }
