[package]
name = "wav1c-ffi"
version = "0.1.0"
edition = "2024"
authors = ["Rafael Caricio <rafael@caricio.com>"]

[lib]
crate-type = ["cdylib", "staticlib", "lib"]

[dependencies]
wav1c = { path = "../wav1c" }
