[package]
name = "wav1c"
version = "0.1.1"
edition = "2024"
description = "Wondrous AV1 encoder written in safe Rust."
license = "MPL-2.0"
repository = "https://github.com/rafaelcaricio/wav1c"
authors.workspace = true
keywords.workspace = true
readme = "../README.md"

[dependencies]
