[package]
name = "wav1c-wasm"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wav1c = { path = "../wav1c" }
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s"
lto = true
